seckit_xss:
  csp:
    checkbox: true
    report-only: false
    default-src: '''self'''
    script-src: '''self'' ''unsafe-inline'' ''unsafe-eval'' http://cdnjs.cloudflare.com http://stackpath.bootstrapcdn.com http://ajax.googleapis.com'
    object-src: ''
    img-src: '''self'' data:'
    media-src: ''
    frame-src: ''
    child-src: ''
    font-src: '''self'' cdn.jsdelivr.net http://cdnjs.cloudflare.com http://fonts.gstatic.com http://use.fontawesome.com'
    connect-src: ''
    report-uri: report-csp-violation
    policy-uri: ''
    style-src: '''self'' ''unsafe-inline''  http://stackpath.bootstrapcdn.com http://fonts.googleapis.com  http://ajax.googleapis.com http://use.fontawesome.com'
    frame-ancestors: ''
    vendor-prefix:
      x: false
      webkit: false
    upgrade-req: false
  x_xss:
    seckit_x_xss_option_disable: Disabled
    seckit_x_xss_option_0: '0'
    seckit_x_xss_option_1: 1;
    seckit_x_xss_option_1_block: '1; mode=block'
    select: 2
seckit_csrf:
  origin: true
  origin_whitelist: ''
seckit_clickjacking:
  js_css_noscript: true
  noscript_message: 'Sorry, you need to enable JavaScript to visit this website.'
  x_frame: '1'
  x_frame_allow_from: ''
seckit_ssl:
  hsts: false
  hsts_subdomains: true
  hsts_max_age: 2592000
  hsts_preload: true
seckit_various:
  from_origin: true
  from_origin_destination: same
  disable_autocomplete: true
  referrer_policy: true
  referrer_policy_policy: no-referrer-when-downgrade
_core:
  default_config_hash: 1QSPl6Lx4K-hAcSOsRUFyntOnghLfpsDzjY6tbhnAVY
seckit_ct:
  expect_ct: false
  max_age: null
  report_uri: ''
  enforce: false
seckit_fp:
  feature_policy: false
  feature_policy_policy: ''
